// pages/api/data.js

export default (req, res) => {
  const data = [
    {
      Name: 'John',
      Age: 25,
      Country: 'USA',
      Email: 'john@example.com',
      Gender: 'Male',
      Role: 'Developer',
    },
    {
      Name: 'Alice',
      Age: 30,
      Country: 'Canada',
      Email: 'alice@example.com',
      Gender: 'Female',
      Role: 'Designer',
    },
    {
      Name: 'Bob',
      Age: 22,
      Country: 'UK',
      Email: 'bob@example.com',
      Gender: 'Male',
      Role: 'Tester',
    },
    {
      Name: 'Eve',
      Age: 28,
      Country: 'Australia',
      Email: 'eve@example.com',
      Gender: 'Female',
      Role: 'Manager',
    },
    {
      Name: 'Charlie',
      Age: 35,
      Country: 'Germany',
      Email: 'charlie@example.com',
      Gender: 'Male',
      Role: 'Architect',
    },
    {
      Name: 'Grace',
      Age: 27,
      Country: 'France',
      Email: 'grace@example.com',
      Gender: 'Female',
      Role: 'Analyst',
    },    {
        Name: 'Eve',
        Age: 28,
        Country: 'Australia',
        Email: 'eve@example.com',
        Gender: 'Female',
        Role: 'Manager',
      },
      {
        Name: 'Charlie',
        Age: 35,
        Country: 'Germany',
        Email: 'charlie@example.com',
        Gender: 'Male',
        Role: 'Architect',
      },
      {
        Name: 'Grace',
        Age: 27,
        Country: 'France',
        Email: 'grace@example.com',
        Gender: 'Female',
        Role: 'Analyst',
      },    {
        Name: 'Eve',
        Age: 28,
        Country: 'Australia',
        Email: 'eve@example.com',
        Gender: 'Female',
        Role: 'Manager',
      },
      {
        Name: 'Charlie',
        Age: 35,
        Country: 'Germany',
        Email: 'charlie@example.com',
        Gender: 'Male',
        Role: 'Architect',
      },
      {
        Name: 'Grace',
        Age: 27,
        Country: 'France',
        Email: 'grace@example.com',
        Gender: 'Female',
        Role: 'Analyst',
      }, {
        Name: 'John',
        Age: 25,
        Country: 'USA',
        Email: 'john@example.com',
        Gender: 'Male',
        Role: 'Developer',
      },
      {
        Name: 'Alice',
        Age: 30,
        Country: 'Canada',
        Email: 'alice@example.com',
        Gender: 'Female',
        Role: 'Designer',
      },
      {
        Name: 'Bob',
        Age: 22,
        Country: 'UK',
        Email: 'bob@example.com',
        Gender: 'Male',
        Role: 'Tester',
      },
      {
        Name: 'Eve',
        Age: 28,
        Country: 'Australia',
        Email: 'eve@example.com',
        Gender: 'Female',
        Role: 'Manager',
      },
      {
        Name: 'Charlie',
        Age: 35,
        Country: 'Germany',
        Email: 'charlie@example.com',
        Gender: 'Male',
        Role: 'Architect',
      },
      {
        Name: 'Grace',
        Age: 27,
        Country: 'France',
        Email: 'grace@example.com',
        Gender: 'Female',
        Role: 'Analyst',
      },    {
          Name: 'Eve',
          Age: 28,
          Country: 'Australia',
          Email: 'eve@example.com',
          Gender: 'Female',
          Role: 'Manager',
        },
        {
          Name: 'Charlie',
          Age: 35,
          Country: 'Germany',
          Email: 'charlie@example.com',
          Gender: 'Male',
          Role: 'Architect',
        },
        {
          Name: 'Grace',
          Age: 27,
          Country: 'France',
          Email: 'grace@example.com',
          Gender: 'Female',
          Role: 'Analyst',
        },    {
          Name: 'Eve',
          Age: 28,
          Country: 'Australia',
          Email: 'eve@example.com',
          Gender: 'Female',
          Role: 'Manager',
        },
        {
          Name: 'Charlie',
          Age: 35,
          Country: 'Germany',
          Email: 'charlie@example.com',
          Gender: 'Male',
          Role: 'Architect',
        },
        {
          Name: 'Grace',
          Age: 27,
          Country: 'France',
          Email: 'grace@example.com',
          Gender: 'Female',
          Role: 'Analyst',
        }, {
            Name: 'John',
            Age: 25,
            Country: 'USA',
            Email: 'john@example.com',
            Gender: 'Male',
            Role: 'Developer',
          },
          {
            Name: 'Alice',
            Age: 30,
            Country: 'Canada',
            Email: 'alice@example.com',
            Gender: 'Female',
            Role: 'Designer',
          },
          {
            Name: 'Bob',
            Age: 22,
            Country: 'UK',
            Email: 'bob@example.com',
            Gender: 'Male',
            Role: 'Tester',
          },
          {
            Name: 'Eve',
            Age: 28,
            Country: 'Australia',
            Email: 'eve@example.com',
            Gender: 'Female',
            Role: 'Manager',
          },
          {
            Name: 'Charlie',
            Age: 35,
            Country: 'Germany',
            Email: 'charlie@example.com',
            Gender: 'Male',
            Role: 'Architect',
          },
          {
            Name: 'Grace',
            Age: 27,
            Country: 'France',
            Email: 'grace@example.com',
            Gender: 'Female',
            Role: 'Analyst',
          },    {
              Name: 'Eve',
              Age: 28,
              Country: 'Australia',
              Email: 'eve@example.com',
              Gender: 'Female',
              Role: 'Manager',
            },
            {
              Name: 'Charlie',
              Age: 35,
              Country: 'Germany',
              Email: 'charlie@example.com',
              Gender: 'Male',
              Role: 'Architect',
            },
            {
              Name: 'Grace',
              Age: 27,
              Country: 'France',
              Email: 'grace@example.com',
              Gender: 'Female',
              Role: 'Analyst',
            },    {
              Name: 'Eve',
              Age: 28,
              Country: 'Australia',
              Email: 'eve@example.com',
              Gender: 'Female',
              Role: 'Manager',
            },
            {
              Name: 'Charlie',
              Age: 35,
              Country: 'Germany',
              Email: 'charlie@example.com',
              Gender: 'Male',
              Role: 'Architect',
            },
            {
              Name: 'Grace',
              Age: 27,
              Country: 'France',
              Email: 'grace@example.com',
              Gender: 'Female',
              Role: 'Analyst',
            }, {
                Name: 'John',
                Age: 25,
                Country: 'USA',
                Email: 'john@example.com',
                Gender: 'Male',
                Role: 'Developer',
              },
              {
                Name: 'Alice',
                Age: 30,
                Country: 'Canada',
                Email: 'alice@example.com',
                Gender: 'Female',
                Role: 'Designer',
              },
              {
                Name: 'Bob',
                Age: 22,
                Country: 'UK',
                Email: 'bob@example.com',
                Gender: 'Male',
                Role: 'Tester',
              },
              {
                Name: 'Eve',
                Age: 28,
                Country: 'Australia',
                Email: 'eve@example.com',
                Gender: 'Female',
                Role: 'Manager',
              },
              {
                Name: 'Charlie',
                Age: 35,
                Country: 'Germany',
                Email: 'charlie@example.com',
                Gender: 'Male',
                Role: 'Architect',
              },
              {
                Name: 'Grace',
                Age: 27,
                Country: 'France',
                Email: 'grace@example.com',
                Gender: 'Female',
                Role: 'Analyst',
              },    {
                  Name: 'Eve',
                  Age: 28,
                  Country: 'Australia',
                  Email: 'eve@example.com',
                  Gender: 'Female',
                  Role: 'Manager',
                },
                {
                  Name: 'Charlie',
                  Age: 35,
                  Country: 'Germany',
                  Email: 'charlie@example.com',
                  Gender: 'Male',
                  Role: 'Architect',
                },
                {
                  Name: 'Grace',
                  Age: 27,
                  Country: 'France',
                  Email: 'grace@example.com',
                  Gender: 'Female',
                  Role: 'Analyst',
                },    {
                  Name: 'Eve',
                  Age: 28,
                  Country: 'Australia',
                  Email: 'eve@example.com',
                  Gender: 'Female',
                  Role: 'Manager',
                },
                {
                  Name: 'Charlie',
                  Age: 35,
                  Country: 'Germany',
                  Email: 'charlie@example.com',
                  Gender: 'Male',
                  Role: 'Architect',
                },
                {
                  Name: 'Grace',
                  Age: 27,
                  Country: 'France',
                  Email: 'grace@example.com',
                  Gender: 'Female',
                  Role: 'Analyst',
                }, {
                    Name: 'John',
                    Age: 25,
                    Country: 'USA',
                    Email: 'john@example.com',
                    Gender: 'Male',
                    Role: 'Developer',
                  },
                  {
                    Name: 'Alice',
                    Age: 30,
                    Country: 'Canada',
                    Email: 'alice@example.com',
                    Gender: 'Female',
                    Role: 'Designer',
                  },
                  {
                    Name: 'Bob',
                    Age: 22,
                    Country: 'UK',
                    Email: 'bob@example.com',
                    Gender: 'Male',
                    Role: 'Tester',
                  },
                  {
                    Name: 'Eve',
                    Age: 28,
                    Country: 'Australia',
                    Email: 'eve@example.com',
                    Gender: 'Female',
                    Role: 'Manager',
                  },
                  {
                    Name: 'Charlie',
                    Age: 35,
                    Country: 'Germany',
                    Email: 'charlie@example.com',
                    Gender: 'Male',
                    Role: 'Architect',
                  },
                  {
                    Name: 'Grace',
                    Age: 27,
                    Country: 'France',
                    Email: 'grace@example.com',
                    Gender: 'Female',
                    Role: 'Analyst',
                  },    {
                      Name: 'Eve',
                      Age: 28,
                      Country: 'Australia',
                      Email: 'eve@example.com',
                      Gender: 'Female',
                      Role: 'Manager',
                    },
                    {
                      Name: 'Charlie',
                      Age: 35,
                      Country: 'Germany',
                      Email: 'charlie@example.com',
                      Gender: 'Male',
                      Role: 'Architect',
                    },
                    {
                      Name: 'Grace',
                      Age: 27,
                      Country: 'France',
                      Email: 'grace@example.com',
                      Gender: 'Female',
                      Role: 'Analyst',
                    },    {
                      Name: 'Eve',
                      Age: 28,
                      Country: 'Australia',
                      Email: 'eve@example.com',
                      Gender: 'Female',
                      Role: 'Manager',
                    },
                    {
                      Name: 'Charlie',
                      Age: 35,
                      Country: 'Germany',
                      Email: 'charlie@example.com',
                      Gender: 'Male',
                      Role: 'Architect',
                    },
                    {
                      Name: 'Grace',
                      Age: 27,
                      Country: 'France',
                      Email: 'grace@example.com',
                      Gender: 'Female',
                      Role: 'Analyst',
                    },
  ];

  res.status(200).json(data);
};
